def forca(count):
    if count == 1:
        print('  _'*4)
        print(' /         I')
        print('/         ( )')
        print('|\n'*5)
    if count == 2:
        print('  _'*4)
        print(' /         I')
        print('/         ( )')
        print('|          |')
        print('|\n'*4)
    if count == 3:
        print('  _'*4)
        print(' /         I')
        print('/         ( )')
        print('|        / |')
        print('|\n'*4)
    if count == 4:
        print('  _'*4)
        print(' /         I')
        print('/         ( )')
        print('|        / | \\')
        print('|\n'*4)
    if count == 5:
        print('  _'*4)
        print(' /         I')
        print('/         ( )')
        print('|        / | \\')
        print('|          |')
        print('|         /')
        print('|\n'*2)
    if count == 6:
        print('  _'*4)
        print(' /         I')
        print('/         ( )')
        print('|        / | \\')
        print('|          |')
        print('|         / \\')
        print('|\n'*2)
